config/routes.rb
Mywikirev::Application.routes.draw do

root :to => "users#new"
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "reviews" =>"reviews#index", :as=>"reviews"
resources :users
resources :sessions
resources :reviews
end

app/models/rev.rb
class Rev < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
attr_accessible :title , :content ,:creator
	
	validates :title,:content,:creator ,:presence =>true
	validates :title,:length=>{ :minimum => 2}
	validates :title,:uniqueness =>true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
private
#to get the current user
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
	@reviews = Review.all
	if current_user
		@reviews = Review.all
		render "index"
	  else
		redirect_to log_in_path, :notice=>"You must first login"
	  end
	end
	
	def show
	@review = Review.find(params[:id])
	end
	
	def new
	@review = Review.new
	end
	def create
	  @review = Review.new(params[:review])
	  
	  if @review.save 
		redirect_to reviews_path, :notice=>"Your review was saved"
	  else
		render "new"
	  end
	end
	
	def edit
	@review = Review.find(params[:id])
	end
	def update
	 @review = Review.find(params[:id])
	 
	 if @review.update_attributes(params[:review])
	 redirect_to reviews_path ,:notice => "Your review has been updated"
	 else
	 render "edit"
	 end
	end
	
	def destroy
	 @review = Review.find(params[:id])
	 @review.destroy
	 redirect_to reviews_path,notice=>"Your review has been deleted"
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end


def create
  user = User.authenticate(params[:email], params[:password])
  if user
    session[:user_id] = user.id
	session[:user_name] = user.email
    redirect_to reviews_path, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to sign_up_path, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to log_in_path, :notice => "Signed up!"
  else
    render "new"
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mywikirev</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<style type="text/css">
body{
background:url(./images/glob.jpg);
}
h1,h2,h3,p,a{
font-family:sans-serif;
margin:0;
}
#user_nav{
text-align:center;
background:#eeeeee;
}
#greet{
font:2em Sans-serif;
text-align:center;
margin:10px;
}
#blog{
text-align:center;
font:1.5em Sans-serif;
margin:10px;
}
.content{
width:960px;
background:transparent;
border:2px solid ;
margin:0 auto;
 -moz-border-radius-topleft: 30px;
    -webkit-border-top-left-radius: 30px;

}
.posts{
padding:20px;
}
.controls{
float:right;
}
.login,.signup{
width:250px;
height:200px;
position:absolute;
top:50%;
left:50%;
margin-top:-125px;
margin-left:-100px;
}
#flash{
text-align:center;
font-size:1.5em;
}
.addrev{
width:400px;
margin:0 auto;
}
.specials{
width:400px;
float:left;
margin-top:30px;
}
.features{
width:400px;
float:right;
margin-top:30px;
}
</style>

  </head>
<body>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>
<div id="flash">
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</div>
<%= yield %>

</body>
</html>

app/views/reviews/edit.html.erb
<h1>edit</h1>

<%= form_for @review do |f| %>
	<p>
	<%= f.label :title %><br />
	<%= f.text_field :title %> 
	</p>
	<p>
	<%= f.label :content %><br />
	<%= f.text_area :content %> 
	</p>
	<p>
	<%= f.submit "Update review "%>


<%end %>

app/views/reviews/index.html.erb
<h1 id="greet">Hello <%= session[:user_name] %></h1>
<h2 id="blog">Blog on Global Warming</h2>
<div class="content">
<% @reviews.each do |review| %>
<div class="posts">
		<div class="controls">
	<% if session[:user_name] == review.creator || session[:user_name] == "admin"  %>
	<p><%= link_to "Edit" ,edit_review_path(review) %>
	<%= link_to "Delete" ,review , :confirm => "Are you Sure?",:method=>:delete %>
	</p>
	<% end %>
	</div>
	<h3> <%= link_to review.title, review %></h3>
	<small>By <%= review.creator %></small>
	<p><%= review.content %></p>

	</div>
	<hr />
<% end %>
<div>
<p><%= link_to "Add a New review ", new_review_path %></p>

app/views/reviews/new.html.erb
<div class="addrev">
<h2>Add a new review <%= session[:user_name] %></h2>

<%= form_for @review do |f| %>
	<p>
	<%= f.label :title %> <br />
	<%= f.text_field :title %> 
	</p>
	<p>
	<%= f.label :content %> <br />
	<%= f.text_area :content	%> 
	</p>
	<p>
<%= f.hidden_field :creator , :value => session[:user_name] %>
	</p>
	<p>
	<%= f.submit "Add a new review " %>
	</p>

<% end %>
</div>

app/views/reviews/show.html.erb
<h2><%= @review.title %> </h2>
<p> <%= @review.content %> </p>
<small> <%= @review.created_at %></small>

app/views/users/new.html.erb
<div id="blog">
<h1>Blog on Global Warming</h1>
</div>

<div class="specials">
<h2>Specialities of this blog</h2>
<ul>
<li>Login System was developed from scratch</li>
<li>Password is encrypted..So safety is assured</li>
<li>Control panel enables you to access content create only by you</li>
</ul>
</div>
<div class="features">
<h2>Features of this blog</h2>
<ul>
<li>One can edit or delete posts created by them only</li>
<li>By above feature we ensure that no one else edits or deletes your post</li>
<li>you can access the blog only after you login</li>
<li>However ,Admin has rights to alter every post</li>
</ul>
</div>
<div class="signup">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email%><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</div>